# 基础
basic:
  # kindle设备上documents目录的路径
  documents:
    macos: /Volumes/Kindle/documents
    windows: F:/documents

  # kindlegen.exe的路径
  kindlegen:
    macos: ~/OneDrive/programs/kindlegen/kindlegen
    windows: D:/OneDrive/programs/kindlegen/kindlegen.exe

# 漫画
manga:
  # 仓库路径
  storage:
    macos: ~/Downloads/manga
    windows: D:/Downloads/漫画/同步

  # 图片最大宽度
  maxWidth: 1280

  # 图片压缩质量
  quality: 80

# 小说
novel:
  # 仓库路径
  storage:
    macos: ~/OneDrive/books/同步
    windows: D:/OneDrive/books/同步

  # 书籍分割的字数
  fileSize: 200000
